appprops:
   redisnodes:
      - localhost:7000
      - localhost:7001
      - localhost:7002
      - localhost:7003
      - localhost:7004
      - localhost:7005
 
    
redis: 
    config: "/Users/anandbose/tmob/Redis/redis-aws-tmob-cluster.yml"     
    ttl: 
      test: 3H